DROP EVENT IF EXISTS eLiquidateActiveLines ;

CREATE EVENT eLiquidateActiveLines
ON SCHEDULE EVERY 10 MINUTE
STARTS CURRENT_TIMESTAMP
ENDS CURRENT_TIMESTAMP + INTERVAL 48 HOUR
ON COMPLETION PRESERVE
DO

    call pliquidateActiveLines();

