SET GLOBAL event_scheduler = ON;
DROP EVENT IF EXISTS eLiquidateActiveLines ;

CREATE EVENT eLiquidateActiveLines
ON SCHEDULE EVERY 1 MONTH
STARTS '2020-08-01'
ENDS CURRENT_TIMESTAMP + INTERVAL 1 YEAR
ON COMPLETION PRESERVE
DO

    call pliquidateActiveLines();

